apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark-master
  ports:
    - name: master-port
      protocol: TCP
      port: 7077
      targetPort: 7077